name: Build and Release Snake Game

on:
  push:
    tags:
      - "v*.*.*"  # Se ejecuta cuando subes un tag como v1.0.0

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Build solution
      run: dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -o ./publish

    - name: Zip the installer
      run: Compress-Archive -Path ./publish/* -DestinationPath SnakeGame.zip

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: SnakeGame.zip
        token: ${{ secrets.GITHUB_TOKEN }}

